//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCare_ProtoType.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctormaster
    {
        public int DocterId { get; set; }
        public string DoctorName { get; set; }
        public string Specialization { get; set; }
        public string Experience { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
    }
}
