//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCare_ProtoType.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class healthcaredbEntities : DbContext
    {
        public healthcaredbEntities()
            : base("name=healthcaredbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminmaster> adminmasters { get; set; }
        public virtual DbSet<doctormaster> doctormasters { get; set; }
        public virtual DbSet<enquirymaster> enquirymasters { get; set; }
        public virtual DbSet<notificationmaster> notificationmasters { get; set; }
    }
}
